//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 10 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `black`.
    var black: RswiftResources.ColorResource { .init(name: "black", path: [], bundle: bundle) }

    /// Color `gray`.
    var gray: RswiftResources.ColorResource { .init(name: "gray", path: [], bundle: bundle) }

    /// Color `gray20`.
    var gray20: RswiftResources.ColorResource { .init(name: "gray20", path: [], bundle: bundle) }

    /// Color `gray30`.
    var gray30: RswiftResources.ColorResource { .init(name: "gray30", path: [], bundle: bundle) }

    /// Color `gray40`.
    var gray40: RswiftResources.ColorResource { .init(name: "gray40", path: [], bundle: bundle) }

    /// Color `gray60`.
    var gray60: RswiftResources.ColorResource { .init(name: "gray60", path: [], bundle: bundle) }

    /// Color `gray70`.
    var gray70: RswiftResources.ColorResource { .init(name: "gray70", path: [], bundle: bundle) }

    /// Color `green`.
    var green: RswiftResources.ColorResource { .init(name: "green", path: [], bundle: bundle) }

    /// Color `white`.
    var white: RswiftResources.ColorResource { .init(name: "white", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 8 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `bookmark`.
    var bookmark: RswiftResources.ImageResource { .init(name: "bookmark", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `house`.
    var house: RswiftResources.ImageResource { .init(name: "house", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `loupe`.
    var loupe: RswiftResources.ImageResource { .init(name: "loupe", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `person_circle`.
    var person_circle: RswiftResources.ImageResource { .init(name: "person_circle", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `plus`.
    var plus: RswiftResources.ImageResource { .init(name: "plus", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `route`.
    var route: RswiftResources.ImageResource { .init(name: "route", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `thumbsup`.
    var thumbsup: RswiftResources.ImageResource { .init(name: "thumbsup", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `thumbsup_filled`.
    var thumbsup_filled: RswiftResources.ImageResource { .init(name: "thumbsup_filled", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }
}