//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 10 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `black`.
    var black: RswiftResources.ColorResource { .init(name: "black", path: [], bundle: bundle) }

    /// Color `gray`.
    var gray: RswiftResources.ColorResource { .init(name: "gray", path: [], bundle: bundle) }

    /// Color `gray20`.
    var gray20: RswiftResources.ColorResource { .init(name: "gray20", path: [], bundle: bundle) }

    /// Color `gray30`.
    var gray30: RswiftResources.ColorResource { .init(name: "gray30", path: [], bundle: bundle) }

    /// Color `gray40`.
    var gray40: RswiftResources.ColorResource { .init(name: "gray40", path: [], bundle: bundle) }

    /// Color `gray60`.
    var gray60: RswiftResources.ColorResource { .init(name: "gray60", path: [], bundle: bundle) }

    /// Color `gray70`.
    var gray70: RswiftResources.ColorResource { .init(name: "gray70", path: [], bundle: bundle) }

    /// Color `green`.
    var green: RswiftResources.ColorResource { .init(name: "green", path: [], bundle: bundle) }

    /// Color `white`.
    var white: RswiftResources.ColorResource { .init(name: "white", path: [], bundle: bundle) }
  }
}